"""Amazon scraper using the official Scrapeless Python SDK + Playwright over CDP.
Under the hood:
- `client.browser.create()` mints a cloud browser session, returning a CDP WS endpoint.
- Playwright connects over CDP, drives the page, returns rendered HTML.
- Parsel parses the HTML into TypedDicts matching DATA_MODEL.md.
"""

from __future__ import annotations

import json
import math
import os
import re
from typing import Any, Dict, List, Optional, TypedDict
from urllib.parse import parse_qsl, urlencode, urljoin, urlparse, urlunparse

from loguru import logger as log
from parsel import Selector
from playwright.async_api import async_playwright
from scrapeless import Scrapeless
from scrapeless.types import ICreateBrowser

DEFAULT_PROXY_COUNTRY = "US"
DEFAULT_SESSION_TTL = 180

# ---------------------------------------------------------------------------
# Schemas — mirror the upstream reference's TypedDicts verbatim
# ---------------------------------------------------------------------------

class ProductPreview(TypedDict):
    """result generated by search scraper"""

    url: str
    title: str
    price: str
    real_price: str
    rating: str
    rating_count: str

class Review(TypedDict):
    title: str
    text: str
    location_and_date: str
    verified: bool
    rating: float

class Product(TypedDict):
    """type hint storage of Amazons product information"""

    name: str
    asin: str
    style: str
    description: str
    stars: str
    rating_count: str
    features: List[str]
    images: List[str]
    info_table: Dict[str, str]

class ProductRef(TypedDict):
    """product Rufus cites in an answer"""

    asin: str
    title: str
    url: str

class RufusAnswer(TypedDict):
    """answer returned by Amazon's Rufus AI shopping assistant"""

    question: str
    answer_text: str
    product_refs: List[ProductRef]

# ---------------------------------------------------------------------------
# Scrapeless plumbing
# ---------------------------------------------------------------------------

def _client() -> Scrapeless:
    if not os.environ.get("SCRAPELESS_API_KEY") and not os.environ.get("SCRAPELESS_KEY"):
        raise RuntimeError(
            "SCRAPELESS_API_KEY env var not set. Sign up at https://app.scrapeless.com"
        )
    if not os.environ.get("SCRAPELESS_API_KEY") and os.environ.get("SCRAPELESS_KEY"):
        os.environ["SCRAPELESS_API_KEY"] = os.environ["SCRAPELESS_KEY"]
    return Scrapeless()

def _add_or_replace_url_parameters(url: str, **params) -> str:
    """adds url parameters or replaces them with new values"""
    parsed_url = urlparse(url)
    query_params = dict(parse_qsl(parsed_url.query))
    query_params.update({k: str(v) for k, v in params.items()})
    updated_url = parsed_url._replace(query=urlencode(query_params))
    return urlunparse(updated_url)

async def _fetch_rendered_html(
    url: str,
    ready_selector: Optional[str] = None,
    *,
    proxy_country: str = DEFAULT_PROXY_COUNTRY,
    retries: int = 1,
) -> str:
    """Discover → extract: mint a session, goto, wait for stable marker, return HTML.

    Includes an Amazon-specific retry around the "Continue shopping" interstitial.
    """
    last_error: Exception | None = None
    for attempt in range(retries + 1):
        client = _client()
        session = client.browser.create(
            ICreateBrowser(proxy_country=proxy_country, session_ttl=DEFAULT_SESSION_TTL)
        )
        ws = session.browser_ws_endpoint
        async with async_playwright() as pw:
            browser = await pw.chromium.connect_over_cdp(ws)
            try:
                page = await browser.new_page()
                await page.goto(url, wait_until="domcontentloaded", timeout=45000)
                # Handle "Continue shopping" interstitial
                try:
                    btn = await page.query_selector("button:has-text('Continue shopping')")
                    if btn:
                        await btn.click()
                        await page.wait_for_load_state("domcontentloaded", timeout=15000)
                except Exception:
                    pass
                if ready_selector:
                    try:
                        await page.wait_for_selector(ready_selector, timeout=15000)
                    except Exception as e:
                        log.warning("wait_for_selector {!r} failed (continuing): {}", ready_selector, e)
                html = await page.content()
                if html and "Continue shopping" not in html[:5000]:
                    return html
                last_error = RuntimeError("interstitial / empty HTML")
            except Exception as e:  # noqa: BLE001
                last_error = e
                log.warning("attempt {} failed: {}", attempt + 1, e)
            finally:
                try:
                    await browser.close()
                except Exception:
                    pass
    # Last resort: even an empty HTML is better than nothing for parse-debug
    if last_error and "html" in dir(last_error):
        return ""
    raise RuntimeError(f"giving up after {retries + 1} attempts: {last_error}")

async def _ask_rufus(
    url: str,
    question: str,
    *,
    proxy_country: str = DEFAULT_PROXY_COUNTRY,
) -> str:
    """Open Rufus on a product page, type a question, and return the rendered answer HTML.

    Rufus is interactive — unlike the read-only `_fetch_rendered_html`, this opens the
    assistant panel, types the question, sends it, and waits for the streamed reply to settle.
    """
    client = _client()
    session = client.browser.create(
        ICreateBrowser(proxy_country=proxy_country, session_ttl=DEFAULT_SESSION_TTL)
    )
    ws = session.browser_ws_endpoint
    async with async_playwright() as pw:
        browser = await pw.chromium.connect_over_cdp(ws)
        try:
            page = await browser.new_page()
            await page.goto(url, wait_until="domcontentloaded", timeout=45000)
            try:
                btn = await page.query_selector("button:has-text('Continue shopping')")
                if btn:
                    await btn.click()
                    await page.wait_for_load_state("domcontentloaded", timeout=15000)
            except Exception:
                pass
            # Open the Rufus panel
            try:
                launcher = await page.query_selector("[data-csa-c-content-id=rufus-launcher], #nav-rufus-disco, [aria-label*='Rufus']")
                if launcher:
                    await launcher.click()
            except Exception:
                pass
            # Type the question and send it
            await page.wait_for_selector("textarea[data-testid=rufus-text-input], textarea[name=rufus-input]", timeout=15000)
            box = await page.query_selector("textarea[data-testid=rufus-text-input], textarea[name=rufus-input]")
            await box.fill(question)
            await page.keyboard.press("Enter")
            # Wait for the streamed answer to settle
            await page.wait_for_selector("[data-testid=rufus-message-assistant], [data-rufus-message-role=assistant]", timeout=30000)
            await page.wait_for_timeout(2500)
            return await page.content()
        finally:
            try:
                await browser.close()
            except Exception:
                pass

# ---------------------------------------------------------------------------
# Search
# ---------------------------------------------------------------------------

def parse_search(html: str, base_url: str) -> List[ProductPreview]:
    """Parse search result page for product previews"""
    sel = Selector(text=html)
    previews: List[ProductPreview] = []
    product_boxes = sel.css("div.s-result-item[data-component-type=s-search-result]")
    for box in product_boxes:
        href = box.css("div>a::attr(href)").get()
        if not href:
            continue
        url = urljoin(base_url, href).split("?")[0]
        if "/slredirect/" in url:
            continue
        rating = box.xpath(".//div[@data-cy='reviews-block']//a[contains(@aria-label, 'out of')]/@aria-label").re_first(r"(\d+\.*\d*) out")
        rating_count = box.xpath(".//div[@data-cy='reviews-block']//a[contains(@aria-label, 'ratings')]/@aria-label").get()
        previews.append(
            {
                "url": url,
                "title": box.css("div>a>h2::attr(aria-label)").get(),
                "price": box.css(".a-price[data-a-size=xl] .a-offscreen::text").get(),
                "real_price": box.xpath(".//div[@data-cy='secondary-offer-recipe']//span[contains(@class, 'a-color-base') and contains(text(), '$')]/text()").get(),
                "rating": float(rating) if rating else None,
                "rating_count": int(rating_count.replace(",", "").replace(" ratings", "")) if rating_count else None,
            }
        )
    log.info(f"parsed {len(previews)} product previews from {base_url}")
    return previews

async def scrape_search(url: str, max_pages: Optional[int] = None) -> List[ProductPreview]:
    """Scrape amazon search pages product previews"""
    log.info(f"{url}: scraping first page")
    first_html = await _fetch_rendered_html(
        url,
        ready_selector="div.s-result-item[data-component-type=s-search-result]",
    )
    results = parse_search(first_html, url)

    # Find total pages from the paging meta
    sel = Selector(text=first_html)
    paging_meta = sel.xpath("//*[@cel_widget_id='UPPER-RESULT_INFO_BAR-0']//span/text()").get() or ""
    total_pages = 1
    try:
        total_results = int(re.findall(r"(?:over\s+)?([\d,]+)\s+results", paging_meta)[0].replace(",", ""))
        results_per_page = int(re.findall(r"\d+-(\d+)", paging_meta)[0])
        total_pages = math.ceil(total_results / results_per_page)
    except (IndexError, ValueError):
        log.warning("could not parse paging meta: {!r}", paging_meta)

    if max_pages and total_pages > max_pages:
        total_pages = max_pages

    log.info(f"{url}: scraping {total_pages} pages")
    for page in range(2, total_pages + 1):
        page_url = _add_or_replace_url_parameters(url, page=page)
        page_html = await _fetch_rendered_html(
            page_url,
            ready_selector="div.s-result-item[data-component-type=s-search-result]",
        )
        results.extend(parse_search(page_html, page_url))

    log.info(f"{url}: found total of {len(results)} product previews")
    return results

# ---------------------------------------------------------------------------
# Reviews
# ---------------------------------------------------------------------------

def parse_reviews(html: str) -> List[Review]:
    """parse review from single review page"""
    sel = Selector(text=html)
    review_boxes = sel.css("#cm-cr-dp-review-list li.review")
    parsed: List[Review] = []
    for box in review_boxes:
        rating = box.css("[data-hook=review-star-rating] ::text").re_first(r"(\d+\.*\d*) out")
        parsed.append(
            {
                "text": "".join(box.css("[data-hook=review-collapsed] ::text").getall()).strip(),
                "title": box.css("*[data-hook=review-title]>span::text").get(),
                "location_and_date": box.css("span[data-hook=review-date] ::text").get(),
                "verified": bool(box.css("span[data-hook=avp-badge] ::text").get()),
                "rating": float(rating) if rating else None,
            }
        )
    return parsed

async def scrape_reviews(url: str) -> List[Review]:
    """scrape product reviews of a given URL of an amazon product"""
    log.info(f"scraping review page: {url}")
    html = await _fetch_rendered_html(url, ready_selector="#cm-cr-dp-review-list")
    reviews = parse_reviews(html)
    log.info(f"scraped {len(reviews)} reviews")
    return reviews

# ---------------------------------------------------------------------------
# Product
# ---------------------------------------------------------------------------

def parse_product(html: str) -> Product:
    """parse Amazon's product page for essential product data"""
    images: List[str] = []
    if color_images := re.findall(r"colorImages':.*'initial':\s*(\[.+?\])},\n", html):
        try:
            images = [img["large"] for img in json.loads(color_images[0])]
        except Exception:
            pass
    if image_gallery := re.findall(r"imageGalleryData'\s*:\s*(\[.+\]),\n", html):
        try:
            images = [img["mainUrl"] for img in json.loads(image_gallery[0])]
        except Exception:
            pass

    sel = Selector(text=html)
    parsed: Product = {
        "name": sel.css("#productTitle::text").get("").strip(),
        "asin": sel.css("input[name=ASIN]::attr(value)").get("").strip(),
        "style": "".join(sel.css("[id^=inline-twister-expanded-dimension-text] ::text").getall()).strip(),
        "description": "\n".join(sel.css("#productDescription p span ::text").getall()).strip(),
        "stars": sel.css("i[data-hook=average-star-rating] ::text").get("").strip(),
        "rating_count": sel.css("span[data-hook=total-review-count] ::text").get("").strip(),
        "features": [value.strip() for value in sel.css("#feature-bullets li ::text").getall() if value.strip()],
        "images": images,
        "info_table": {},
    }
    info_table: Dict[str, str] = {}
    for row in sel.css("#productDetails_detailBullets_sections1 tr"):
        label = row.css("th::text").get("").strip()
        value = row.css("td::text").get("").strip()
        if not value:
            value = row.css("td span::text").get("").strip()
        if label:
            info_table[label] = value
    info_table["Customer Reviews"] = sel.xpath("//td[div[@id='averageCustomerReviews']]//span[@class='a-icon-alt']/text()").get()
    rank = sel.xpath("//tr[th[text()=' Best Sellers Rank ']]//td//text()").getall()
    info_table["Best Sellers Rank"] = " ".join([text.strip() for text in rank if text.strip()])
    parsed["info_table"] = info_table
    return parsed

async def scrape_product(url: str) -> List[Product]:
    """scrape Amazon.com product (and any sibling variants)"""
    url = url.split("/ref=")[0]
    asin = url.split("/dp/")[-1].rstrip("/")
    log.info(f"scraping product {url}")
    html = await _fetch_rendered_html(
        url,
        ready_selector="#productDetails_detailBullets_sections1 tr",
    )
    variants: List[Product] = [parse_product(html)]

    # If product has variants — scrape all of them
    _variation_data = re.findall(r'dimensionValuesDisplayData"\s*:\s*({.+?}),\n', html)
    if _variation_data:
        try:
            variant_asins = [a for a in json.loads(_variation_data[0]) if a != asin]
            log.info(f"scraping {len(variant_asins)} variants: {variant_asins}")
            for variant_asin in variant_asins:
                variant_url = f"https://www.amazon.com/dp/{variant_asin}"
                v_html = await _fetch_rendered_html(
                    variant_url,
                    ready_selector="#productDetails_detailBullets_sections1 tr",
                )
                variants.append(parse_product(v_html))
        except Exception as e:
            log.warning("failed to parse variants: {}", e)
    return variants

# ---------------------------------------------------------------------------
# Rufus
# ---------------------------------------------------------------------------

def parse_rufus(html: str, question: str) -> RufusAnswer:
    """parse Rufus's answer panel for the assistant reply and any cited products"""
    sel = Selector(text=html)
    answer_text = "\n".join(
        t.strip()
        for t in sel.css("[data-testid=rufus-message-assistant] ::text, [data-rufus-message-role=assistant] ::text").getall()
        if t.strip()
    )
    product_refs: List[ProductRef] = []
    for card in sel.css("[data-testid=rufus-message-assistant] a[href*='/dp/'], [data-rufus-message-role=assistant] a[href*='/dp/']"):
        href = card.css("::attr(href)").get()
        if not href:
            continue
        url = urljoin("https://www.amazon.com", href).split("?")[0]
        asin_match = re.findall(r"/dp/([A-Z0-9]{10})", url)
        product_refs.append(
            {
                "asin": asin_match[0] if asin_match else "",
                "title": "".join(card.css("::text").getall()).strip(),
                "url": url,
            }
        )
    return {
        "question": question,
        "answer_text": answer_text,
        "product_refs": product_refs,
    }

async def scrape_rufus(url: str, question: str) -> List[RufusAnswer]:
    """ask Rufus a product question on an Amazon product page and parse the answer"""
    url = url.split("/ref=")[0]
    log.info(f"asking Rufus about {url}: {question!r}")
    html = await _ask_rufus(url, question)
    answer = parse_rufus(html, question)
    log.info(f"Rufus answered with {len(answer['product_refs'])} product refs")
    return [answer]

def to_dict(obj: Any) -> Any:
    """Recursively convert TypedDicts/lists to plain dicts/lists for JSON output."""
    if isinstance(obj, dict):
        return {k: to_dict(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [to_dict(x) for x in obj]
    return obj
